variables:
  DOCKER_REGISTRY_IMAGE_NAME: flux-ilias/cron-base
  DEV_DOCKER_REGISTRY_IMAGE: $DEV_DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_IMAGE_NAME
  DOCKER_REGISTRY_IMAGE: $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_IMAGE_NAME
  PHP_VERSIONS: "7.2 7.3 7.4 8.0"

build:
  stage: build
  script:
    - echo -n $DEV_DOCKER_REGISTRY_PASSWORD | docker login -u $DEV_DOCKER_REGISTRY_USER --password-stdin $DEV_DOCKER_REGISTRY_URL;
      for php_version in $PHP_VERSIONS; do
        docker build . --pull --build-arg ILIAS_BASE_IMAGE=$DEV_DOCKER_REGISTRY_URL/flux-ilias/ilias-base:php$php_version -t $DEV_DOCKER_REGISTRY_IMAGE:php$php_version;
        docker push $DEV_DOCKER_REGISTRY_IMAGE:php$php_version;
      done;
      docker logout $DEV_DOCKER_REGISTRY_URL;
  only:
    - develop

FluxPublishUtils:
  stage: build
  image: docker-registry.fluxpublisher.ch/flux-publish-utils:latest
  script:
    - "false"
  only:
    - main

publish:
  stage: deploy
  script:
    - echo -n $DEV_DOCKER_REGISTRY_PASSWORD | docker login -u $DEV_DOCKER_REGISTRY_USER --password-stdin $DEV_DOCKER_REGISTRY_URL;
      for php_version in $PHP_VERSIONS; do
        docker pull $DEV_DOCKER_REGISTRY_IMAGE:php$php_version;
      done;
      docker logout $DEV_DOCKER_REGISTRY_URL;
    - echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_URL;
      for php_version in $PHP_VERSIONS; do
        docker tag $DEV_DOCKER_REGISTRY_IMAGE:php$php_version $DOCKER_REGISTRY_IMAGE:php$php_version;
        docker push $DOCKER_REGISTRY_IMAGE:php$php_version;
      done;
      docker logout $DOCKER_REGISTRY_URL;
  only:
    - main
